version: "3"
services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: syncthing-main-node
    depends_on:
      - nextcloud
    volumes:
      - /opt/M122/nextcloud/data:/var/syncthing/nextcloud:ro
    environment:
      - TZ=Europe/Zurich
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped

  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    restart: unless-stopped
    expose:
      - 5432

  nextcloud:
    image: nextcloud:27.1.3
    container_name: nextcloud
    hostname: nextcloud-main-node
    depends_on:
      - db
    volumes:
      - /opt/M122/nextcloud/data:/var/www/html/data/
      - /opt/M122/nextcloud/config:/var/www/html/config/
      - /opt/M122/nextcloud/docker:/docker-entrypoint-hooks.d/before-starting/
    environment:
      - TZ=Europe/Zurich
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=db
    ports:
      - 1880:80
    restart: unless-stopped
